from models import InternshipOpportunity

SEED_INTERNSHIPS = [
    InternshipOpportunity(
        id="job-1",
        title="AI & LLM Systems Engineer Intern",
        company="Anthropic Labs / FutureTech",
        domain="AI/ML",
        location="Remote",
        stipend="₹50,000 / mo",
        required_skills=["Python", "TensorFlow", "PyTorch", "REST APIs", "Git"],
        optional_skills=["Vector DBs", "LangChain", "Docker"],
        min_gpa=8.0,
        description="Build autonomous agent workflows, evaluate LLM prompts, and optimize RAG pipelines for high-throughput production deployments.",
        deadline="2026-09-01",
        apply_url="https://anthropic.com/careers/intern"
    ),
    InternshipOpportunity(
        id="job-2",
        title="Full Stack Web Developer Intern",
        company="Nexus Cloud Solutions",
        domain="Full Stack",
        location="Bengaluru, India",
        stipend="₹38,000 / mo",
        required_skills=["React", "Node.js", "SQL", "REST APIs", "Git"],
        optional_skills=["TypeScript", "TailwindCSS", "AWS"],
        min_gpa=7.5,
        description="Develop interactive student dashboards, state management pipelines, and high-performance microservices for enterprise clients.",
        deadline="2026-08-30",
        apply_url="https://nexuscloud.io/careers"
    ),
    InternshipOpportunity(
        id="job-3",
        title="Data Science & Machine Learning Intern",
        company="Quantum Analytics Inc.",
        domain="Data Science",
        location="Remote",
        stipend="₹35,000 / mo",
        required_skills=["Python", "SQL", "TensorFlow", "Pandas"],
        optional_skills=["Scikit-Learn", "Tableau", "PyTorch"],
        min_gpa=7.8,
        description="Analyze large-scale student interaction datasets, build predictive recommendation models, and produce business intelligence dashboards.",
        deadline="2026-09-05",
        apply_url="https://quantumanalytics.ai/jobs"
    ),
    InternshipOpportunity(
        id="job-4",
        title="Generative AI Research Intern",
        company="DeepVision Labs",
        domain="AI/ML",
        location="Bengaluru, India",
        stipend="₹55,000 / mo",
        required_skills=["Python", "PyTorch", "TensorFlow", "Git"],
        optional_skills=["OpenCV", "CUDA", "Transformers"],
        min_gpa=8.5,
        description="Experiment with fine-tuning multimodal foundation models, neural architecture search, and latency optimization on GPU clusters.",
        deadline="2026-08-28",
        apply_url="https://deepvision.ai/internships"
    ),
    InternshipOpportunity(
        id="job-5",
        title="Backend API & Distributed Systems Intern",
        company="ScaleUp PayTech",
        domain="Full Stack",
        location="Hybrid (Mumbai)",
        stipend="₹40,000 / mo",
        required_skills=["Node.js", "SQL", "REST APIs", "Git"],
        optional_skills=["Redis", "PostgreSQL", "Docker", "Go"],
        min_gpa=7.0,
        description="Design robust, low-latency RESTful APIs and database schemas for real-time high-concurrency payment processing.",
        deadline="2026-09-10",
        apply_url="https://scaleup.com/careers"
    ),
    InternshipOpportunity(
        id="job-6",
        title="Frontend UI/UX Engineer Intern",
        company="Stripe / DesignCraft",
        domain="UI/UX",
        location="Remote",
        stipend="₹36,000 / mo",
        required_skills=["React", "TypeScript", "TailwindCSS", "Git"],
        optional_skills=["Figma", "Framer Motion", "Next.js"],
        min_gpa=7.2,
        description="Create responsive, sleek web interfaces with smooth animations, accessible component systems, and intuitive design workflows.",
        deadline="2026-09-02",
        apply_url="https://stripe.com/jobs/intern-ui"
    ),
    InternshipOpportunity(
        id="job-7",
        title="Cyber Security & Application Security Intern",
        company="ShieldCyber Security",
        domain="Cyber Security",
        location="Hyderabad, India",
        stipend="₹32,000 / mo",
        required_skills=["Python", "REST APIs", "Git", "SQL"],
        optional_skills=["Wireshark", "Penetration Testing", "Linux"],
        min_gpa=7.5,
        description="Conduct vulnerability scans, inspect API endpoints for auth flaws, and assist in automating SOC security playbooks.",
        deadline="2026-09-15",
        apply_url="https://shieldcyber.io/careers"
    ),
    InternshipOpportunity(
        id="job-8",
        title="Associate Product Manager (APM) Intern",
        company="ProductSpace",
        domain="Product",
        location="Remote",
        stipend="₹30,000 / mo",
        required_skills=["Problem Solving", "Communication", "Data Analysis"],
        optional_skills=["SQL", "Figma", "Mixpanel"],
        min_gpa=7.0,
        description="Gather user requirements, draft feature specifications, analyze retention funnels, and collaborate with engineering teams.",
        deadline="2026-09-08",
        apply_url="https://productspace.com/apm"
    ),
    InternshipOpportunity(
        id="job-9",
        title="Cloud Infrastructure & DevOps Intern",
        company="AWS CloudOps Partner",
        domain="Full Stack",
        location="Pune, India",
        stipend="₹38,000 / mo",
        required_skills=["Python", "Git", "REST APIs"],
        optional_skills=["Docker", "Kubernetes", "Terraform", "AWS"],
        min_gpa=7.5,
        description="Automate CI/CD deployment pipelines, manage containerized clusters, and optimize cloud infrastructure costs.",
        deadline="2026-09-12",
        apply_url="https://awscloudops.com/careers"
    ),
    InternshipOpportunity(
        id="job-10",
        title="Computer Vision Research Intern",
        company="RoboTech Dynamics",
        domain="AI/ML",
        location="Bengaluru, India",
        stipend="₹48,000 / mo",
        required_skills=["Python", "PyTorch", "TensorFlow"],
        optional_skills=["OpenCV", "ROS", "C++"],
        min_gpa=8.2,
        description="Develop real-time object detection and spatial tracking algorithms for autonomous mobile robotic fleets.",
        deadline="2026-09-04",
        apply_url="https://robotech.ai/jobs"
    ),
    InternshipOpportunity(
        id="job-11",
        title="Data Engineer Intern",
        company="DataPipeline Global",
        domain="Data Science",
        location="Remote",
        stipend="₹37,000 / mo",
        required_skills=["Python", "SQL", "Git"],
        optional_skills=["Spark", "Airflow", "Snowflake"],
        min_gpa=7.6,
        description="Build ETL data pipelines, clean heterogeneous data streams, and optimize BigQuery SQL analytical queries.",
        deadline="2026-09-14",
        apply_url="https://datapipeline.com/careers"
    ),
    InternshipOpportunity(
        id="job-12",
        title="Natural Language Processing (NLP) Intern",
        company="LinguaAI Systems",
        domain="AI/ML",
        location="Remote",
        stipend="₹45,000 / mo",
        required_skills=["Python", "PyTorch", "REST APIs"],
        optional_skills=["HuggingFace", "BERT", "Vector DBs"],
        min_gpa=8.0,
        description="Train domain-specific embeddings, build sentiment analysis models, and integrate entity extraction pipelines.",
        deadline="2026-09-06",
        apply_url="https://lingua.ai/careers"
    ),
    InternshipOpportunity(
        id="job-13",
        title="Mobile App Developer Intern (React Native / Flutter)",
        company="MobilityX",
        domain="Full Stack",
        location="Hybrid (Bengaluru)",
        stipend="₹34,000 / mo",
        required_skills=["React", "Git", "REST APIs"],
        optional_skills=["React Native", "Flutter", "Firebase"],
        min_gpa=7.3,
        description="Build cross-platform mobile apps, integrate biometric auth, and craft smooth 60fps UI animations.",
        deadline="2026-09-11",
        apply_url="https://mobilityx.app/careers"
    ),
    InternshipOpportunity(
        id="job-14",
        title="Bioinformatics & Computational Biology Intern",
        company="GeneCode Tech",
        domain="Data Science",
        location="Remote",
        stipend="₹42,000 / mo",
        required_skills=["Python", "SQL", "Git"],
        optional_skills=["Biopython", "R", "Nextflow"],
        min_gpa=8.0,
        description="Process genomic sequencing datasets, evaluate variant classification pipelines, and build interactive analytical tools.",
        deadline="2026-09-18",
        apply_url="https://genecode.org/internships"
    ),
    InternshipOpportunity(
        id="job-15",
        title="AI Ethics & Governance Intern",
        company="Responsible AI Institute",
        domain="AI/ML",
        location="Remote",
        stipend="₹30,000 / mo",
        required_skills=["Problem Solving", "Communication", "Python"],
        optional_skills=["Audit Tools", "Policy Frameworks"],
        min_gpa=7.5,
        description="Audit LLM output safety, evaluate bias mitigation benchmarks, and draft governance policy compliance briefs.",
        deadline="2026-09-20",
        apply_url="https://responsibleai.org/careers"
    ),
    InternshipOpportunity(
        id="job-16",
        title="Site Reliability Engineer (SRE) Intern",
        company="CloudScale Networks",
        domain="Full Stack",
        location="Chennai, India",
        stipend="₹36,000 / mo",
        required_skills=["Python", "REST APIs", "Git", "SQL"],
        optional_skills=["Linux", "Prometheus", "Grafana"],
        min_gpa=7.4,
        description="Monitor system uptime, debug distributed microservice latencies, and automate infrastructure failover runbooks.",
        deadline="2026-09-07",
        apply_url="https://cloudscale.net/sre-intern"
    ),
    InternshipOpportunity(
        id="job-17",
        title="Quantitative Developer Intern",
        company="AlphaTrading Capital",
        domain="Data Science",
        location="Mumbai, India",
        stipend="₹60,000 / mo",
        required_skills=["Python", "SQL", "Git"],
        optional_skills=["C++", "Pandas", "Time Series"],
        min_gpa=8.8,
        description="Implement high-frequency statistical arbitrage algorithms, backtest market signals, and optimize execution speeds.",
        deadline="2026-08-29",
        apply_url="https://alphatrading.com/quant"
    ),
    InternshipOpportunity(
        id="job-18",
        title="Product Designer (UI/UX) Intern",
        company="VisualFlow Studio",
        domain="UI/UX",
        location="Remote",
        stipend="₹28,000 / mo",
        required_skills=["Problem Solving", "Communication"],
        optional_skills=["Figma", "Design Systems", "Prototyping"],
        min_gpa=7.0,
        description="Design high-fidelity wireframes, conduct user usability interviews, and create component libraries for web and mobile.",
        deadline="2026-09-16",
        apply_url="https://visualflow.design/careers"
    )
]
